version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on: 
      - mongo

  # Frontend React Service
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - "3000:80"
    depends_on:
      - backend

   # --- NEW MONGO SERVICE ---
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# --- NEW MONGO VOLUME ---
volumes:
  mongo-data: