version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  # Frontend React Service
  frontend:
    build: ./frontend
    volumes:
      # Map src directory for hot-reloading
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      # Default Create React App port is 3000
      - "3000:80"
    depends_on:
      - backend